id: osic-pulmonary-fibrosis-progression
name: OSIC Pulmonary Fibrosis Progression
competition_type: simple
awards_medals: true
prizes:
  - position: 1
    value: 30000
  - position: 2
    value: 15000
  - position: 3
    value: 10000
description: timeseriesgym/competitions/osic-pulmonary-fibrosis-progression/description.md

dataset:
  answers: osic-pulmonary-fibrosis-progression/prepared/private/test.csv
  sample_submission: osic-pulmonary-fibrosis-progression/prepared/public/sample_submission.csv

grader:
  name: laplace-log-likelihood
  grade_fn: timeseriesgym.competitions.osic-pulmonary-fibrosis-progression.grade:grade

preparer: timeseriesgym.competitions.osic-pulmonary-fibrosis-progression.prepare:prepare
